### ISSUE TITLE
Proposal: Trigger

### ISSUE THREAD

**Issue by tamalsaha** [kube-ci/issues#3]
```
kubectl crate --raw=/apis/kube.ci/v1alpha1/triggers/namespaces/<ns>

apiVersion: kube.ci/v1alpha1
kind: Trigger
metadata:
  generate-name: testing-blah
workflow: []
request: |
  apiversion: v1
  kind: namespace
  metadata:
    name: mydemons
  spec:

// k8s.io/apimachinery/pkg/runtime
Object runtime.RawExtension
```
